server:
  port: 8080
management:
  server:
    port: 8081
    servlet:
      context-path: /monitor   #actuator\u7684\u8BBF\u95EE\u8DEF\u5F84
  endpoint:
    shutdown:
      enabled: true    # \u5F00\u542Fshutdown
