spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mybatis_db?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: 123
    type: com.mysql.cj.jdbc.MysqlDataSource


  cache:
    # \u7F13\u5B58\u7C7B\u578B
    type: ehcache
    ehcache:
      config: 'classpath:ehcache.xml'
  redis:
    # Redis\u6570\u636E\u5E93\u7D22\u5F15\uFF08\u9ED8\u8BA4\u4E3A0\uFF09
    database: 0
    # Redis\u670D\u52A1\u5668\u5730\u5740
    host: localhost
    # Redis\u670D\u52A1\u5668\u8FDE\u63A5\u7AEF\u53E3
    port: 6379
    # \u8FDE\u63A5\u8D85\u65F6\u65F6\u95F4\uFF08\u6BEB\u79D2\uFF09
    timeout: 50

# \u914D\u7F6E\u65E5\u5FD7\u8F93\u51FA\u7EA7\u522B\u4EE5\u89C2\u5BDFSQL\u7684\u6267\u884C\u60C5\u51B5\uFF1A
logging:
  level:
    com:
      tengxt:
        springbootrediscache:
          mapper: debug

# mapper xml\u5B9E\u73B0\u626B\u63CF\u8DEF\u5F84
mybatis:
  mapper-locations: classpath:mapper/*.xml
